/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java2d;

import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public class frameFilm extends javax.swing.JFrame {
    
    String[] Judul={"Kode Film","Judul Film","Genre Film","Tahun","Asal","Stok"};
    String[] Field={"KodeFilm","Judul","Genre","Tahun","Asal","Stok"};
    String SQL = "SELECT*FROM film";
    int[] Lebar ={120,400,250,150,300,180};
//    String[] Judul={"Username","Password","Level"};
//   int[] Lebar ={200,200,150};

    /**
     * Creates new form frameFilm
     */
    public frameFilm() {
        ConfigDB_2D praktikum = new ConfigDB_2D();
        initComponents();
        this.setLocationRelativeTo(null);
        
        praktikum.settingJudulTabel(TabelFilm, Judul);
        praktikum.settingLebarKolom(TabelFilm, Lebar);
        praktikum.tampilTabel(TabelFilm, SQL, Judul);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TabelFilm = new javax.swing.JTable();
        txtJudul = new javax.swing.JTextField();
        txtGenre = new javax.swing.JTextField();
        txtAsal = new javax.swing.JTextField();
        txtStok = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTahun = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtKode = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnCetak = new javax.swing.JButton();
        txtCari = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TabelFilm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelFilm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelFilmMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelFilm);

        jLabel6.setText("Asal Film");

        txtTahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTahunActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        jLabel1.setText("Kode Film");

        jLabel2.setText("Judul Film");

        jLabel3.setText("Genre");

        jLabel5.setText("Stok");

        txtKode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKodeActionPerformed(evt);
            }
        });

        jLabel4.setText("Tahun");

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jLabel7.setText("Cari Data");

        btnCetak.setText("Cetak");

        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addComponent(jLabel4)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel7))
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCari, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                .addComponent(txtKode)
                                .addComponent(txtJudul)
                                .addComponent(txtGenre)
                                .addComponent(txtAsal)
                                .addComponent(txtStok))
                            .addComponent(txtTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(128, 128, 128)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnUbah, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSimpan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCetak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSimpan))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUbah))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(btnClear)
                    .addComponent(txtAsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(btnCetak))
                    .addComponent(txtCari, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>                        

    private void txtTahunActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {                                          
        try {
            if(txtKode.getText().trim().equals("")){
                JOPtionPane.showMessageDialog(null, "Kode Film Belum Terisi");
                txtKode.requestFocus();
            } else if(txtJudul.getText().trim().equals("")){
                JOPtionPane.showMessageDialog(null, "Judul Film Belum Terisi");
                txtJudul.requestFocus();
            } else if(txtGenre.getText().trim().equals("")){
                JOPtionPane.showMessageDialog(null, "Genre Film Belum Terisi");
                txtGenre.requestFocus();
            } else if(txtTahun.getText().trim().equals("")){
                JOPtionPane.showMessageDialog(null, "Tahun Film Belum Terisi");
                txtTahun.requestFocus();
            } else if(txtAsal.getText().trim().equals("")){
                JOPtionPane.showMessageDialog(null, "Asal Film Belum Terisi");
                txtAsal.requestFocus();
            } else if(txtStok.getText().trim().equals("")){
                JOPtionPane.showMessageDialog(null, "Stok Film Belum Terisi");
                txtStok.requestFocus();
            } else if(new ConfigDB_2D().DuplicateKey("film", "KodeFilm", txtKode.getText())){
                JOPtionPane.showMessageDialog(null, "Kode Film Sudah Terdaftar");
                txtJudul.requestFocus();
            } else {
                String[] field = {"KodeFilm","Judul","Genre","Tahun","Asal","Stok"};
                String[] isi = {txtKode.getText(),txtJudul.getText(),txtGenre.getText(),txtTahun.getText(),txtAsal.getText(),txtStok.getText()};
                new ConfigDB_2D().SimpanDinamis("film", field, isi);
                new ConfigDB_2D().settingJudulTabel(TabelFilm, Judul);
                new ConfigDB_2D().tampilTabel(TabelFilm, SQL, Judul);
                new ConfigDB_2D().settingLebarKolom(TabelFilm, Lebar);
            }
        } catch (Exception e){
            System.out.println(e.toString());
        }
    }                                         

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {                                        
        try {
            String[] field = {"Judul","Genre","Tahun","Asal","Stok"};
            String[] isi = {txtJudul.getText(),txtGenre.getText(),txtTahun.getText(),txtAsal.getText(),txtStok.getText()};
            new ConfigDB_2D().UbahDinamis("film", "KodeFilm", txtKode.getText(), field, field);
            JOptionPane.showMessageDialog(null, "Data Berhasil diubah");
            new ConfigDB_2D().settingJudulTabel(TabelFilm, Judul);
            new ConfigDB_2D().tampilTabel(TabelFilm, SQL, Judul);
            new ConfigDB_2D().settingLebarKolom(TabelFilm, Lebar);
        } catch (Exception e){
            System.out.println(e.toString());
        }
    }                                       

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {                                         
        new ConfigDB_2D().HapusDinamis("film", "KodeFilm", txtKode.getText());
        JOptionPane.showMessageDialog(null, "Berhasil Dihapus");
        new ConfigDB_2D().settingJudulTabel(TabelFilm, Judul);
        new ConfigDB_2D().tampilTabel(TabelFilm, SQL, Judul);
        new ConfigDB_2D().settingLebarKolom(TabelFilm, Lebar);
        txtKode.setText("");
        txtJudul.setText("");
        txtGenre.setText("");
        txtTahun.setText("");
        txtAsal.setText("");
        txtStok.setText("");
    }                                        

    private void txtKodeActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        txtKode.setText("");
        txtJudul.setText("");
        txtGenre.setText("");
        txtTahun.setText("");
        txtAsal.setText("");
        txtStok.setText("");
    }                                        

    private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {                                    
        // TODO add your handling code here:
        String Cari = "SELECT*FROM film WHERE KodeFilm LIKE '%"+txtCari.getText()+"%'OR Judul LIKE '%"+txtCari.getText()+"%'";
        new ConfigDB_2D().settingJudulTabel(TabelFilm, Judul);
        new ConfigDB_2D().tampilTabel(TabelFilm, SQL, Judul);
        new ConfigDB_2D().settingLebarKolom(TabelFilm, Lebar);
    }                                   

    private void TabelFilmMouseClicked(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
        int row = TabelFilm.getSelectedRow();
        txtKode.setText(TabelFilm.getModel().getValueAt(row,0).toString());
        txtJudul.setText(TabelFilm.getModel().getValueAt(row,1).toString());
        txtGenre.setText(TabelFilm.getModel().getValueAt(row,2).toString());
        txtTahun.setText(TabelFilm.getModel().getValueAt(row,3).toString());
        txtAsal.setText(TabelFilm.getModel().getValueAt(row,4).toString());
        txtStok.setText(TabelFilm.getModel().getValueAt(row,5).toString());
    }                                      

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameFilm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTable TabelFilm;
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAsal;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtGenre;
    private javax.swing.JTextField txtJudul;
    private javax.swing.JTextField txtKode;
    private javax.swing.JTextField txtStok;
    private javax.swing.JTextField txtTahun;
    // End of variables declaration                   
}